disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - weak_delegate
excluded:
  - Carthage
  - Pods
  - Build
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true
    
function_body_length:
  warning: 50
  error: 100
  
function_parameter_count:
  warning: 5
  error: 8
    
type_body_length:
  warning: 200
  error: 350
    
file_length:
  warning: 400
  error: 1000
  ignore_comment_only_lines: true
    
cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length: 2
  max_length: 40

reporter: "xcode"
